version: "3"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: Postgres123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - common
networks:
  common:
